name: Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  TyposCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@v1.22.7
        with:
          config: ./typos.toml
          
  UnitTest:
    runs-on: ubuntu-latest
    env:
      BINANCE_PROXY_URL: "http://51.83.140.52:16301"
      BINANCE_TESTNET: "true"
      BINANCE_API_KEY: "u4L8MG2DbshTfTzkx2Xm7NfsHHigvafxeC29HrExEmah1P8JhxXkoOu6KntLICUc"
      BINANCE_API_SECRET: "hBZEqhZUUS6YZkk7AIckjJ3iLjrgEFr5CRtFPp5gjzkrHKKC9DAv4OH25PlT6yq5"
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version-file: './v2/go.mod'
        cache: true
        cache-dependency-path: './v2/go.sum'
    - name: Format
      run: ./check.sh format
    - name: Vet
      run: ./check.sh vet
    - name: UnitTest
      run: ./check.sh unittest
    - name: IntegrationTest
      run: ./check.sh integration
